development: &defaults
  images_in_row: 5
  admin_email: sashastanko@mail.ru
  category_preview_photos_count: 4
  password: "secret"

test:
  <<: *defaults

production:
  <<: *defaults
  admin_email: elutic@gmail.com